### ISSUE TITLE
Change "stats" backend url

### ISSUE THREAD

**Issue by jsmadja** [poliva/ggposrv#17]
Hi,

The dns neogeodb.com is not available anymore. You should use 195.154.127.240:8765 instead of neogeodb.com:8765 in stats page.

By the way, do you know if this page is viewed ? (Is Google Analytics configured ?)

**Comment by poliva** [comment]
Thanks for notifying me, just fixed the issue.

I have analytics setup, the stats page has between 50 and 120 pageviews per day, and between 2000-2500 pageviews/month.

Here's a screenshot comparing the last two months:
![screen shot 2016-05-30 at 12 14 21](https://cloud.githubusercontent.com/assets/1238981/15646860/758ccbfa-2660-11e6-86db-5a0b8a40e25d.png)

**Comment by jsmadja** [comment]
Yeah that's cool :)

2016-05-30 12:18 GMT+02:00 Pau Oliva notifications@github.com:
