### ISSUE TITLE
Roms sorting suggestion.

### ISSUE THREAD

**Issue by 3xcl4m4t10n** [poliva/ggposrv#3]
Hello team,

Here I am bothering you again. I was thinking about navigate throught the roms is a pain in the ass. I was thinking on a sorting method for fav games and here it is a little "reconstruction" i made:

http://www.bastantebastante.com/wp-content/Otros/EX1.png
http://www.bastantebastante.com/wp-content/Otros/EX2.png

I don't know if it is very complicated but i think we need something to do with the huge list of games. I love to have all the games because i want to try new titles time by time but i normally only play few titles and is a pain change the room to check new players.

Thanks for reading and hope it can help (but i am sure that you actually have a similar idea like this).

**Comment by 3xcl4m4t10n** [comment]
Added favourite lobbies functionality: add/remove favourite by double-clicking game on the game list, filter favourites from the settings menu (thanks @pokeshark)

Can we close this issue?

**Comment by poliva** [comment]
sure :+1:
